# Dockerfile.vuln
FROM node:16.13.0

# This version has known vulnerabilities in node & openssll
RUN node --version && npm --version

# Trigger Trivy secret scanner
ENV AWS_SECRET_ACCESS_KEY="FAKEKEY123456"

CMD ["node"]
