# Dockerfile.vuln-debian
FROM debian:bullseye

# Outdated vulnerable package
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libssl1.1=1.1.1n-0+deb11u3 \
      curl && \
    rm -rf /var/lib/apt/lists/*

# Fake secret to trigger Trivy secret scanner
ENV AWS_SECRET_ACCESS_KEY="FAKEKEY123456"

CMD ["openssl", "version"]
