apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ $.Chart.Name }}-{{ $.Values.stage }}-github-actions"
  labels:
    app: {{ $.Chart.Name }}
    stage: "{{ $.Values.stage }}"
spec:
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      stage: "{{ $.Values.stage }}"
  maxUnavailable: {{ default "1" $.Values.maxUnavailable | quote }}
