apiVersion: v1
kind: Service
metadata:
  name: {{ include "dummy-chart.name" . }}
  labels:
    {{- include "dummy-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "dummy-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
