name: Helm chart checks

on:
  push:
    branches: [ main, master ]
    paths:     # run only when charts or action files change
      - 'charts/**'
      - '.github/actions/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'charts/**'
      - '.github/actions/**'
  workflow_dispatch:       # manual run with optional inputs
    inputs:
      chart-path:
        description: 'Path to the Helm chart'
        required: true
        default: 'charts/my-awesome-chart'
      values-dir:
        description: 'Dir with *-values.yaml files (defaults to chart path)'
        required: false
        default: ''

jobs:
  helm-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0   # pin the version you prefer

      - name: Lint chart (strict)
        uses: ./.github/actions/helm-lint
        with:
          chart_path: ${{ github.event.inputs.chart-path || 'charts/my-awesome-chart' }}

      - name: Template render check
        uses: ./.github/actions/helm-template
        with:
          chart_path: ${{ github.event.inputs.chart-path || 'charts/my-awesome-chart' }}
          values_dir: ${{ github.event.inputs.values-dir || '' }}
          # extra_args: "--namespace test --kube-version 1.29.2"
