name: Lint with kube-linter

on:
  push:
    branches:
      - main
      - master
    paths:
      - ./k8s/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ./k8s/*
  workflow_dispatch:
    inputs:
      output-file-format:
        description: 'Output file format for kube-linter scan results'
        required: true
        type: choice
        default: json
        options:
          - sarif
          - plain
          - json
      directory:
        description: 'Directory containing kubernetes resources and helm charts. This won''t ingest wildcards'
        required: true
        type: string
        default: './k8s'  

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      - name: Set default values for inputs for non-workflow_dispatch triggers
        id: fix-inputs
        run: |
          echo "output-file-format=${{ (inputs.output-file-format || 'json') }}" >> $GITHUB_OUTPUT
          echo "directory=${{ (inputs.directory || './k8s/sample') }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Create results directory for report files
        shell: bash
        run: mkdir -p ../results

      - name: Install kube-linter manually
        run: |
          curl -sSLo kube-linter.tar.gz https://github.com/stackrox/kube-linter/releases/download/v0.6.6/kube-linter-linux.tar.gz
          tar -xzf kube-linter.tar.gz
          sudo mv kube-linter /usr/local/bin/

      - name: Scan yaml files with kube-linter
        id: kube-linter-action-scan
        shell: bash
        run: |
          echo "Scanning directory: ${{ steps.fix-inputs.outputs.directory }}"
          kube-linter lint ${{ steps.fix-inputs.outputs.directory }} --format ${{ steps.fix-inputs.outputs.output-file-format }} > ../results/kube-linter.${{ steps.fix-inputs.outputs.output-file-format }}
        continue-on-error: true

      - name: Create absolute path to results
        id: results-path
        shell: bash
        run: |
          echo "folder=$(realpath ../results)" >> $GITHUB_OUTPUT

      - name: Get current ISO8601 date
        id: date
        if: always()
        run: |
          iso8601Date=$(date +'%Y%m%d%H%M%S%z')
          echo "iso8601=$iso8601Date" >> $GITHUB_OUTPUT

      - name: Upload report zip file
        if: ${{ env.ACT != 'true' && steps.results-path.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: kube-linter-results-${{ steps.date.outputs.iso8601 }}
          path: ${{ steps.results-path.outputs.folder }}
        continue-on-error: true

      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]
