name: GitVersion & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Needed to create a GitHub release

jobs:
  version-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required by GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.3.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1

      - name: Print calculated version
        run: echo "Calculated version: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.gitversion.outputs.fullSemVer }}
          name: Release v${{ steps.gitversion.outputs.fullSemVer }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
