name: Version & Release

on:
  push:
    branches:
      - main  # or 'release/**' based on your strategy
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semver }}
    steps:
      - uses: actions/checkout@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0

      - name: Show calculated version
        run: echo "Version is ${{ steps.gitversion.outputs.semver }}"

      # Optional: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.gitversion.outputs.semver }}
          name: Release v${{ steps.gitversion.outputs.semver }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
